# Generated by Django 5.2.12 on 2026-05-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('transaction', 'Транзакция'), ('payment_success', 'Успешная оплата'), ('payment_failed', 'Ошибка оплаты'), ('order_cancelled', 'Заказ отменён'), ('system', 'Системное уведомление')], default='system', max_length=50)),
                ('transaction_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_processed', '-created_at'], name='notificatio_is_proc_a393b2_idx')],
            },
        ),
    ]
